### ISSUE TITLE
jquery/jquery and facebook/react compare graph do not represent real star count comparison

### ISSUE THREAD

**Issue by joelhandwell** [nambrot/github-star-growth#1]
As of 2016 July 7th, facebook/react have 39729 stars and jquery/jquery have 38862 stars. And the graph in http://github-star-growth.nambrot.com/ shows jquery have more stars which does not reflect the reality. Reporting here.

**Comment by nambrot** [comment]
Thank you for reporting. I haven't gone around and recalculate star counts, as its quite expensive to do for larger projects. I would definitely be interested in letting others step in and do the hosting if that is of interest
