### ISSUE TITLE
Page down

### ISSUE THREAD

**Issue by jklmli** [nambrot/github-star-growth#2]
The page is blocked in Chrome with a certificate security error.

Bypassing the certificate error lands you on a different, unrelated page.

**Comment by nambrot** [comment]
Thanks for opening the issue. Unfortunately I didnt have the time to keep hosting and maintaining the site, so I took it down

**Comment by jklmli** [comment]
Ah, I understand.  I suggest removing it from the project description to avoid any confusion.

Thanks for all your work!

**Comment by nambrot** [comment]
Thanks for the suggestions. Done
